server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
    hostname: 52.14.165.19
    nonSecurePort: ${server.port}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId:  ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://52.14.165.19:8761/eureka/      

spring:
  application:
    name: product
  jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

  datasource:
        url: jdbc:mysql://52.14.165.19:3306/ms_product?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver 
        
        