server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
    nonSecurePort: ${server.port}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId:  ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/      

spring:
  application:
    name: product
  jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create

  datasource:
        url: jdbc:mysql://localhost:3306/ms_product?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver 
        
        