server:
  port: 8083

eureka:
  instance:
    status-page-url: http://52.14.162.212:8083/info
    health-check-url: http://52.14.162.212.208:8083/info
    home-page-url: http://52.14.162.212:8083/info
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId:  ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/      

spring:
  application:
    name: product
  jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

  datasource:
        url: jdbc:mysql://localhost:3306/ms_product?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver 
        
        